In [249]:
import pandas as pd
import math
import numpy as np
df = pd.read_csv("play_tennis.csv")
df

    day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

In [277]:
# P(yes) , P(No)
Y = 0 
N = 0 
L = len(df['play'])
for i in range(0,len(df["play"])):
    if df['play'][i] =='Yes':
        Y+=1
    else:
        N += 1
print(Y,N)
P_Yes = Y/len(df['play'])
P_No = N/len(df['play'])

9 5

###### class entropy H(D):

In [276]:
E_Class = -1* ((P_Yes* np.log2(P_Yes)) + (P_No*np.log2(P_No)))
print("Data Entropy H(D) = " , E_Class)

Data Entropy H(D) =  0.9402859586706311

###### Entropy of column 'wind' wrt target column

In [253]:
#feature: 'wind'
weak = 0
strong = 0
Wk_No =0
Wk_Yes=0
St_No =0
St_Yes=0
for i in range(0,len(df['wind'])):
    if df['wind'][i]=="Weak":
        weak +=1
    if df['wind'][i]=="Strong":
        strong += 1
for i in range(0,len(df["wind"])):
    if df['wind'][i]=="Weak" and df['play'][i]=="Yes":
        Wk_Yes += 1
    if df['wind'][i]=="Weak" and df['play'][i]=="No":
        Wk_No += 1
    if df['wind'][i]=='Strong' and df['play'][i]=="Yes":
        St_Yes +=1
    if df['wind'][i]=='Strong' and df['play'][i]=='No':
        St_No += 1
Prob_Wk_Yes = Wk_Yes / weak 
Prob_Wk_No = Wk_No / weak
Prob_St_Yes = St_Yes / strong
Prob_St_No = St_No / strong
print("P(Yes|Weak): ", Prob_Wk_Yes, "\nP(No|Weak): " ,Prob_Wk_No , "\nP(Yes|Strong): ",Prob_St_Yes, "\nP(No|Strong):",Prob_St_No )

P(Yes|Weak):  0.75
P(No|Weak):  0.25
P(Yes|Strong):  0.5
P(No|Strong): 0.5

In [254]:
# entropy of weak:
E_weak = -1*((Prob_Wk_Yes* (np.log2(Prob_Wk_Yes))) + Prob_Wk_No* (np.log2(Prob_Wk_No)))
# entropy of strong:
E_strong = -1*((Prob_St_Yes* (np.log2(Prob_St_Yes))) + Prob_St_No* (np.log2(Prob_St_No)))
print("Entropy of week: " , E_weak ,"\nEntropy of strong: ",E_strong)

Entropy of week:  0.8112781244591328
Entropy of strong:  1.0

###### Entropy of column 'humidity' wrt target column

In [256]:
high = 0
norm = 0
H_Yes = 0
H_No = 0
Norm_No = 0
Norm_Yes = 0
for i in range(0,len(df['humidity'])):
    if df['humidity'][i]=="High":
        high +=1
    if df['humidity'][i]=="Normal":
        norm += 1
for i in range(0,len(df["humidity"])):
    if df['humidity'][i]=="High" and df['play'][i]=="Yes":
        H_Yes += 1
    if df['humidity'][i]=="High" and df['play'][i]=="No":
        H_No += 1
    if df['humidity'][i]=='Normal' and df['play'][i]=="Yes":
        Norm_Yes +=1
    if df['humidity'][i]=='Normal' and df['play'][i]=='No':
        Norm_No += 1

In [257]:
prob_H_Yes = H_Yes/high
prob_H_No = H_No = H_No/high
prob_Norm_Yes = Norm_Yes/norm
prob_Norm_No = Norm_No/norm
print(prob_Norm_Yes)

0.8571428571428571

In [258]:
E_High = -1 * ((prob_H_Yes*(np.log2(prob_H_Yes))) + prob_H_No*(np.log2(prob_H_No)))
print("Entropy of high: " ,E_High)
E_Normal = -1 * ((prob_Norm_Yes*(np.log2(prob_Norm_Yes))) + prob_Norm_No*(np.log2(prob_Norm_No)))
print("Entropy of normal: " , E_Normal)

Entropy of high:  0.9852281360342515
Entropy of normal:  0.5916727785823275

###### Entropy of column 'temp' wrt target column

In [260]:
# temp
hot = 0
mild = 0
cool = 0
hot_Yes = 0
mild_Yes = 0
cool_Yes = 0
hot_No = 0
mild_No = 0
cool_No = 0
for i in range(0,len(df['temp'])):
    if df['temp'][i]=="Hot":
        hot +=1
    if df['temp'][i]=="Mild":
        mild += 1
    if df['temp'][i]=="Cool":
        cool += 1
for i in range(0,len(df["temp"])):
    if df['temp'][i]=="Hot" and df['play'][i]=="Yes":
        hot_Yes += 1
    if df['temp'][i]=="Hot" and df['play'][i]=="No":
        hot_No += 1
    if df['temp'][i]=='Mild' and df['play'][i]=="Yes":
        mild_Yes +=1
    if df['temp'][i]=='Mild' and df['play'][i]=='No':
        mild_No += 1
    if df['temp'][i]=='Cool' and df['play'][i]=="Yes":
        cool_Yes +=1
    if df['temp'][i]=='Cool' and df['play'][i]=='No':
        cool_No += 1

In [261]:
prob_hot_No = hot_No/hot
prob_hot_yes = hot_Yes/hot
prob_mild_yes = mild_Yes/mild
prob_mild_No = mild_No/mild
prob_cool_yes = cool_Yes/cool
prob_cool_No  = cool_No/cool

In [262]:
E_hot  = -1* ( (prob_hot_No*(np.log2(prob_hot_No)))  +  (prob_hot_yes*(np.log2(prob_hot_yes))) )
E_mild = -1* ( (prob_mild_yes * (np.log2(prob_mild_yes ))) + (prob_mild_No *(np.log2(prob_mild_No ))) )
E_cool = -1* ( (prob_cool_yes)*(np.log2(prob_cool_yes)) + (prob_cool_No*(np.log2(prob_cool_No))) )

###### Entropy of column 'outlook' wrt target column

In [264]:
sunny = 0
overcast = 0
rain  = 0
sunny_Yes = 0
sunny_No = 0
overcast_Yes = 0
overcast_No = 0
rain_Yes = 0
rain_No = 0
for i in range(0,len(df['outlook'])):
    if df['outlook'][i]=="Sunny":
        sunny +=1
    if df['outlook'][i]=="Overcast":
        overcast += 1
    if df['outlook'][i]=="Rain":
        rain += 1
for i in range(0,len(df["outlook"])):
    if df['outlook'][i]=="Sunny" and df['play'][i]=="Yes":
        sunny_Yes += 1
    if df['outlook'][i]=="Sunny" and df['play'][i]=="No":
        sunny_No += 1
    if df['outlook'][i]=='Overcast' and df['play'][i]=="Yes":
        overcast_Yes +=1
    if df['outlook'][i]=='Overcast' and df['play'][i]=='No':
        overcast_No += 1
    if df['outlook'][i]=='Rain' and df['play'][i]=="Yes":
        rain_Yes +=1
    if df['outlook'][i]=='Rain' and df['play'][i]=='No':
        rain_No += 1
prob_sunny_No = sunny_No/sunny
prob_sunny_yes = sunny_Yes/sunny
prob_oc_yes = overcast_Yes/overcast
prob_oc_No = overcast_No/overcast
prob_rain_yes = rain_Yes/rain
prob_rain_No  = rain_No/rain

In [265]:
E_sunny  = -1* ( (prob_sunny_No*(np.log2(prob_sunny_No)))  +  (prob_sunny_yes*(np.log2(prob_sunny_yes))) )
E_overcast = -1* ( (prob_oc_yes * (np.log2(prob_oc_yes ))) + 0 )
E_rain = -1* ( (prob_rain_yes)*(np.log2(prob_rain_yes)) + (prob_rain_No *(np.log2(prob_rain_No ))) )

#### Informtion gains from different features

In [267]:
IG1 = E_Class - (((sunny/L)*E_sunny) + ((overcast/L)*E_overcast) + ((rain/L)*E_rain))
print("Information Gain [outlook]:  ", IG1)

IG2 = E_Class - ( ((hot/L)*E_hot) + ((mild/L)*E_mild) + ((cool/L)*E_cool) )
print("Information Gain [Temp]:     " , IG2)

IG3 = E_Class - (((high/L)*E_High) + ((norm/L)*E_Normal))
print("Information Gain [Humidity]: ",IG3)

IG4 = E_Class - (((weak/L)*E_weak) + ((strong/L)*E_strong))
print("Information Gain [Wind]:     " ,IG4)

Information Gain [outlook]:   0.24674981977443933
Information Gain [Temp]:      0.02922256565895487
Information Gain [Humidity]:  0.15183550136234159
Information Gain [Wind]:      0.04812703040826949

##### relization: need to make a function for entrpy now (should have doen it before)

In [302]:
# for clas entropy
def classEntropy(col):
    unq,count = np.unique(col , return_counts=True)
#    print(unq,count)
    s = 0    
    for i in count:
        s += i/(len(col)) * np.log2(i/(len(col)))    
    s *= (-1)
    return s

In [472]:
def informationGain (v1,v2):   
    unq_v1 , countV1 = np.unique(v1 , return_counts=True)
    unq_v2 , countV2 = np.unique(v2 , return_counts=True)
#   print(unq_v2 , countV2)
    arr_yes = []
    arr_no  = []    
    for j in unq_v1: 
        yeses = 0
        nos  = 0         
        for k in range(len(v1)):
            if j == v1[k]:
                if  v2[k] == 'Yes':
                    yeses += 1
                else:
                    nos += 1
        arr_yes.append (yeses)
        arr_no.append (nos)        
    summ = 0
    arr_sum = []
    for i in range(0,len(unq_v1)):
        summ = 0        
        if (arr_yes[i]== 0):
            summ += -1 *((arr_no[i]/(countV1[i]) * np.log2(arr_no[i]/(countV1[i]))) )
            
        elif (arr_no[i]== 0):
            summ += -1 *((arr_yes[i]/(countV1[i]) * np.log2(arr_yes[i]/(countV1[i]))) )         
        else:
            summ += -1 *((arr_yes[i]/(countV1[i]) * np.log2(arr_yes[i]/(countV1[i]))) )
            summ += -1 *((arr_no[i]/(countV1[i]) *np.log2(arr_no[i]/(countV1[i]))) )      
        arr_sum.append(summ)  
#     print(arr_sum)
    E_split = 0
    
    for i in range(len(countV1)):
        E_split += arr_sum[i] * countV1[i]/len(v2)  
#     print(E_split)
    Ent_Class = classEntropy(v2)
    I = Ent_Class - E_split  #EntClass = E_Class -> calculated in cell 3    
    print((I))    
    return I

In [473]:
#### splitting data
data1 = []
for i in df['outlook'].unique():
    data1.append(df[df['outlook']==i])

In [474]:
sunny_df = pd.DataFrame(data1[0])

In [475]:
sunny_df

    day outlook  temp humidity    wind play
0    D1   Sunny   Hot     High    Weak   No
1    D2   Sunny   Hot     High  Strong   No
7    D8   Sunny  Mild     High    Weak   No
8    D9   Sunny  Cool   Normal    Weak  Yes
10  D11   Sunny  Mild   Normal  Strong  Yes

In [476]:
overcast_df= pd.DataFrame(data1[1])
overcast_df

    day   outlook  temp humidity    wind play
2    D3  Overcast   Hot     High    Weak  Yes
6    D7  Overcast  Cool   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes

In [477]:
rainy_df= pd.DataFrame(data1[2])
rainy_df

    day outlook  temp humidity    wind play
3    D4    Rain  Mild     High    Weak  Yes
4    D5    Rain  Cool   Normal    Weak  Yes
5    D6    Rain  Cool   Normal  Strong   No
9   D10    Rain  Mild   Normal    Weak  Yes
13  D14    Rain  Mild     High  Strong   No

In [478]:
# splitting next feature
data2 = []
for i in df['temp'].unique():
    data2.append(df[df['temp']==i])   
hot_df = pd.DataFrame(data2[0])
mild_df = pd.DataFrame(data2[1])
cool_df = pd.DataFrame(data2[2])

In [479]:
hot_df

    day   outlook temp humidity    wind play
0    D1     Sunny  Hot     High    Weak   No
1    D2     Sunny  Hot     High  Strong   No
2    D3  Overcast  Hot     High    Weak  Yes
12  D13  Overcast  Hot   Normal    Weak  Yes

In [480]:
mild_df

    day   outlook  temp humidity    wind play
3    D4      Rain  Mild     High    Weak  Yes
7    D8     Sunny  Mild     High    Weak   No
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
13  D14      Rain  Mild     High  Strong   No

In [481]:
cool_df

  day   outlook  temp humidity    wind play
4  D5      Rain  Cool   Normal    Weak  Yes
5  D6      Rain  Cool   Normal  Strong   No
6  D7  Overcast  Cool   Normal  Strong  Yes
8  D9     Sunny  Cool   Normal    Weak  Yes

In [483]:
print("Information Gains from split points" )
i1 = informationGain (np.array(sunny_df['temp']) , np.array(sunny_df['play']) )
i2 = informationGain (np.array(sunny_df['humidity']) , np.array(sunny_df['play']))
i3 = informationGain(np.array(sunny_df['wind']) , np.array(sunny_df['play']))
i4 = informationGain(np.array(mild_df['humidity']) , np.array(mild_df['play']))
i5 = ENTROPY(np.array(mild_df['wind']) , np.array(mild_df['play']))
i6 = ENTROPY(np.array(rainy_df['temp']) , np.array(rainy_df['play']))
i7 = ENTROPY(np.array(rainy_df['humidity']) , np.array(rainy_df['play']))
i8 = ENTROPY(np.array(rainy_df['wind']) , np.array(rainy_df['play']))

Information Gains from split points
0.5709505944546686
0.9709505944546686
0.01997309402197478
0.2516291673878229
0.0
0.01997309402197478
0.01997309402197478
0.9709505944546686

In [484]:
data3 = []
for i in rainy_df['wind'].unique():
    data3.append(rainy_df[rainy_df['wind'] == i])
weak_df = pd.DataFrame(data3[0])
strong_df = pd.DataFrame(data3[1])

In [446]:
weak_df

   day outlook  temp humidity  wind play
3   D4    Rain  Mild     High  Weak  Yes
4   D5    Rain  Cool   Normal  Weak  Yes
9  D10    Rain  Mild   Normal  Weak  Yes

In [447]:
strong_df

    day outlook  temp humidity    wind play
5    D6    Rain  Cool   Normal  Strong   No
13  D14    Rain  Mild     High  Strong   No

In [463]:
def Predict (test):
    label = ''
    if test[0] == 'Overcast':
        label = 'Yes'
    if test[0] == 'Rain':
        if test[3] == 'Weak':
            label ='No'
        elif test[3] == 'Strong':
            label ='Yes'
    if test[0] == 'Sunny':
        if test[3] == 'Hot':
            label = 'No'
        elif test[3] == 'Cool':
            label = 'Yes'
        elif test[3] ==  'Mild':
            label = 'Yes'                
    return label

In [471]:
test  = ['Rain' , 'Hot' , 'Normal' , 'Strong']
Predict(test)

'Yes'